# In order to enable environmental substitution, it is necessary to include all potential configurations in this
# configuration file. Otherwise, the environment variables will not be automatically added to the ResourceConfig
# (`mapstructure:",remain"`).

loglevel: info

source:
  type: filesystem

  # Filesystem config
  filesystem:
    path: /tmp/source.txt

  # HashiCorp Vault config
  hashicorpvault:
    token:
    authMethod: kubernetes
    address: https://localhost:8200

destination:
  type: filesystem

  # Filesystem config
  filesystem:
    path: /tmp/destination.txt
