{{- if and .Values.storage.enabled (not .Values.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lifeboat.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifeboat.labels" $ | nindent 4 }}
  {{- with .Values.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end -}}
