apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backup.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}

  jobTemplate:
    metadata:
      labels:
        {{- include "backup.labels" $ | nindent 8 }}
    spec:

      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "metamodel.selectorLabels" $ | nindent 8 }}
        spec:
          serviceAccountName: {{ include "backup.serviceAccountName" . }}

          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 8 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 12 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:

                {{- range $key, $value := .Values.envValueFrom }}
                - name: {{ $key | quote }}
                  valueFrom:
                    {{- tpl (toYaml $value) $ | nindent 16 }}
                {{- end }}
                {{- range $key, $value := .Values.env }}
                - name: {{ $key | quote }}
                  value: {{ $value }}
                {{- end }}

              envFrom:
                {{- range $value := .Values.envSecretNames }}
                - secretRef:
                    name: {{ $value | quote }}
                {{- end }}
                {{- range $value := .Values.envConfigMapNames }}
                - configMapRef:
                    name: {{ $value | quote }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 12 }}
              volumeMounts:
                {{- with .Values.volumeMounts }}
                  {{- toYaml . | nindent 12 }}
                {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          volumes:
            {{- with .Values.volumes }}
              {{- toYaml . | nindent 8 }}
            {{- end }}

  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end -}}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  suspend: {{ .Values.suspend }}
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone }}
  {{- end -}}
