apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: pvc
  containers:
    - command: ["/bin/echo"]
      args: ["hello world"]
      volumeMounts:
        - mountPath: /tmp/test
          name: backup
